### ISSUE TITLE
#2 Add the ability for companies to log in 

### ISSUE THREAD

**Issue by StunnaDawg** [StunnaDawg/job-board#2]
# Feature Description
In order to implement a job board we need a way for individual users from a company to create an account. This feature has nothing to do with actually implementing job listings, but is a preliminary task for adding user authentication.

## Tasks

- [ ] Add log in/sign up pages
- [ ]  Persist user log in status by checking for the current user's session when they first load the application
- [ ] Add a modal that pops up while waiting for user log out to finish
