### ISSUE TITLE
#3 Add the ability for authenticated users to create, edit, and delete job listings 

### ISSUE THREAD

**Issue by StunnaDawg** [StunnaDawg/job-board#3]
# Feature Description
Once user authentication is implemented we can focus on the main priority for this round of features which is job listings. In this first feature we just need the ability for users to create, edit, and delete job listings. We will focus on payments and publishing job listings in another feature. Only authenticated users should be able to create job listings so these pages should only be accessible if the user is logged in.

## Tasks

- [ ] Add My Listings page
- [ ] Add New/Edit Listing forms
- [ ] Add a preview of the job listing on the new/edit forms
- [ ] Add the ability to delete listings
