### ISSUE TITLE
#4 Add the ability for users to publish job listings 

### ISSUE THREAD

**Issue by StunnaDawg** [StunnaDawg/job-board#4]
# Feature
This feature is fairly simple in that it only focuses on adding the ability for users to pay to publish their job listings and/or extend their current job listings. This does not cover the page for other people to view public job listings.

## Tasks

- [ ] Add the ability for users to pay to extend/publish job listings
- [ ] Add an order confirmation page to direct users to after a successful payment
- [ ] Add proper badges that display the status and time remaining on the my job listings page
