### ISSUE TITLE
#5 Public Job Listing Page

### ISSUE THREAD

**Issue by StunnaDawg** [StunnaDawg/job-board#5]
This feature is the final job listing feature and is all about giving the public the ability to view published job listings. This feature should include a page for viewing all public job listings, the ability to filter job listings, and the ability to hide/favorite job listings. Hiding/favoriting job listings should be persisted for the user so if they come back on the same device they will keep their favorite/hidden jobs.

## Tasks
 

- [ ] Add a publicly accessible job listing page for viewing published listings
- [ ] Add filters to the job listing page
- [ ] Add hide/favourite buttons to each job listing
- [ ] When a job is hidden a toast message should pop up that lets the user undo the favouriting of a job
